### ISSUE TITLE
StyleFrame __init__ doesn't accept numpy array as input

### ISSUE THREAD

**Issue by ruy-sevalho** [DeepSpace2/StyleFrame#101]
Hi there. I'm using python 3.9 and latest styleframe release. I tried initiating a StyleFrame instance with an numpy array and got an an type error:
`TypeError: StyleFrame __init__ doesn't support ndarray`

I just created a panda dataframe first than passed it on to the Styleframe and it works fine, but it seems an easy fix.

**Comment by DeepSpace2** [comment]
Hi, thanks for the suggestion. I'll add it in the next version

**Comment by DeepSpace2** [comment]
Some basic usage examples:

```python
>>> StyleFrame(np.array([1, 2]))
   0
0  1
1  2

>>> StyleFrame(np.array([1, 2]), columns=['a'])
   a
0  1
1  2

>>> StyleFrame(np.array([[1, 2], [3, 4]]))
   0  1
0  1  2
1  3  4

>>> StyleFrame(np.array([[1, 2], [3, 4]]), columns=['a'])
   a  1
0  1  2
1  3  4

>>> StyleFrame(np.array([[1, 2], [3, 4]]), columns=['a', 'b'])
   a  b
0  1  2
1  3  4
```
