### ISSUE TITLE
API to style categorical variables

### ISSUE THREAD

**Issue by jnothman** [DeepSpace2/StyleFrame#104]
It is often useful to style columns having a `pd.CategoricalDtype`, by either:
* being supplied a mapping from category name/code to background colour.
* being supplied a mapping from category name/code to Styler.
* selecting `len(dtype.categories)` colours from a matplotlib colormap (qualitative or otherwise).

So for example we might allow for:

```py
StyleFrame(df).add_categorical_conditional_formatting(style_map={"a": Styler(font_color="red"), "b": Styler(font_color="green"), "c": Styler(font_color="blue")})
```
or
```py
StyleFrame(df).add_categorical_conditional_formatting(style_bg_cmap="Pastel1"})
```
which would perform the following for each column
```py
cmap = matplotlib.cm.get_cmap(style_bg_cmap)
col_style_map = dict(zip(col.dtype.categories, cmap(len(col.dtype.categories))))
```

Conditional formatting would be applied using a [`CellIsRule("=", category)`](https://openpyxl.readthedocs.io/en/stable/_modules/openpyxl/formatting/rule.html#CellIsRule) for each category value in each column in range.

**Comment by DeepSpace2** [comment]
Can this not be achieved with the already available methods (albeit in a more explicit way)?

**Comment by jnothman** [comment]
I find this feature is possible but hard to achieve with both excel and
StyleFrame. It takes several steps and is hard to find/imagine for the
user.

I think of StyleFrame not merely as facilitating the functionality it can
provide, but also:

* Providing a mapping between pandas concepts and excel concepts
* Providing visibility to excel features that a pandas user might be
interested in when presenting a dataframe to a spreadsheet user.

In this vein, making it easier to style pandas Categoricals (or generally
discrete values) makes sense. But maybe I'm just missing which existing API
you refer to.

**Comment by jnothman** [comment]
How would you recommend styling categorical variables with the current API, @DeepSpace2?

**Comment by DeepSpace2** [comment]
Are you able to provide an example `pd.DataFrame` and the output sheet that you envision `StyleFrame(df).add_categorical_conditional_formatting(style_map={"a": Styler(font_color="red"), "b": Styler(font_color="green"), "c": Styler(font_color="blue")})` to output?

**Comment by jnothman** [comment]
Let's say that
```py
style_map = {"a": Styler(font_color="red"), "b": Styler(font_color="green"), "c": Styler(font_color="blue")}
sf.add_categorical_conditional_formatting(style_map=style_map)
```
translates roughly to:
```py
sf = StyleFrame(df)
for value, styler in style_map.items():
    sf = sf.apply_style_by_indexes(sf == value, styler)
```

**Comment by jnothman** [comment]
Ideally, however, it would be implemented with conditional formatting so that the styles do not need to be stored on each cell.

**Comment by jnothman** [comment]
And ideally, provisions would be made to use the categorical dtype's cardinality to select from a colour palette...

**Comment by DeepSpace2** [comment]
Ah, I see.

The current API does support conditional formatting, but only `ColorScaleRule` (wrapped by [`StyleFrame.add_color_scale_conditional_formatting`](https://styleframe.readthedocs.io/en/latest/styleframe.html#styleframe.StyleFrame.add_color_scale_conditional_formatting)).

However, the above example can be implemented without it, using quite an explicit code:

```python
style_map = {"a": Styler(font_color="red"), "b": Styler(font_color="green"), "c": Styler(font_color="blue")}
sf = StyleFrame({'1': ['a', 'b'],
                 '2': ['c', 'd']})
for value, styler in style_map.items():
    for col in sf.columns:
        sf.apply_style_by_indexes(sf[sf[col] == value], styler, cols_to_style=col)
```

generating

![image](https://user-images.githubusercontent.com/6841988/122099300-8887ba00-ce1a-11eb-98c6-1011dc291e91.png)

**Comment by jnothman** [comment]
I agree it's not hard to do; the point is to support:
* increased visibility of this styling approach for discrete-valued columns.
* using a matplotlib colormap or other arbitrary palette where the user is ambivalent about the specific colors used.
