### ISSUE TITLE
Question - How to export the fomat/style to multiple sheets of an existing excel file/new excel file 

### ISSUE THREAD

**Issue by SSMK-wq** [DeepSpace2/StyleFrame#114]
Hi, I am new to StyleFrame and currently using python 3.7, pandas 1.3.4, and openpyxl 3.0.9

My data has below formatting

a) Freeze panes (first 3 columns are frozen)
b) some of the columns headers have different color
c) each alternating cell has different color

It can be downloaded   [dummy_fold_data.xlsx](https://github.com/DeepSpace2/StyleFrame/files/8122496/dummy_fold_data.xlsx)

But the challenge comes in when I have to manipulate the data inside this sheet and store it in multiple sheets of a single excel output file (`out.xlsx`).

I do the below manipulation to split data from input file `dummy_fold_data`

```
writer = pd.ExcelWriter('out.xlsx', engine='xlsxwriter')
for (cust, reg), v in cdf.groupby(['COL1','COL2']):
    v.to_excel(writer, sheet_name=f"DATA_{cust}_{reg}")
writer.save()
```
But the problem is `out.xlsx` doesn't retain the format of the `dummy_fold_data.xlsx`.

I want each of the work sheet within the `out.xlsx` retain the same format as `dummy_fold_data.xlsx`.

When I used the styleframe `read_style=True`, it just reads them as is. but how can I do the above manipulation and copy the same formatting mentioned above to each of the sheet in `out.xlsx`?

I expect my output to be like as shown below (in out.xlsx)

![image](https://user-images.githubusercontent.com/30723825/155276567-e3d48964-b627-463d-8c9e-246a6bc142ef.png)

![image](https://user-images.githubusercontent.com/30723825/155276647-40a00f1c-7df5-4bce-ac42-4c2464cb3391.png)

**Comment by jnothman** [comment]
Perhaps https://github.com/Sydney-Informatics-Hub/copy_xlsx_styles suits your needs??

**Comment by SSMK-wq** [comment]
@jnothman  - thanks. will check that out. but was reading docs while I am traveling. 

does it mean just the below one line of code in cmd line will copy the format of master sheet to all sheets in child sheet?

`usage: copy_xlsx_styles.py [-h] style_worksheet data_worksheet output_xlsx`
