### ISSUE TITLE
Does this package require xlrd dependency ?

### ISSUE THREAD

**Issue by sreerajkksd** [DeepSpace2/StyleFrame#115]
i was going through the sourcecode here and it looks like xlrd was never actually imported in the source code ? Do we really need it?
If we really need it, can we support the latest versions of xlrd ?

**Comment by DeepSpace2** [comment]
I believe it is a left over from the days that `xlrd` supported `xlsx` files. I just ran the tests in an environment without `xlrd` and they all passed. I'll remove `xlrd` as a dependency in the next release.
