### ISSUE TITLE
Q: Save image to styleFrame?

### ISSUE THREAD

**Issue by mitcharka** [DeepSpace2/StyleFrame#118]
Hi,

I'm using StyleFrame for some time now and it's been of great help to me.
Now I run into slightly different aim, I need to insert image to dataFrame cell and save it.
I managed to do that with pandas and "xlsxwriter" with a simple code as bellow, but I cannot figure how to do that with styleFrame
Anyone can help?

```
file_logo_img = "logo.png"
writer = pd.ExcelWriter(folder_test + "img_test.xlsx", engine="xlsxwriter")
df.to_excel(writer, index=False, header=None, sheet_name="Test")
worksheet = writer.sheets["Test"]
worksheet.insert_image(1, 4, file_logo_img)
writer.save()
```

Im using:
Styleframe 4.0.0
XlsxWritter 3.0.2

**Comment by mitcharka** [comment]
I didn't posted SF code, so here it is if needed.

```
excel_writer = StyleFrame.ExcelWriter(save_file)
sf = StyleFrame(df, Styler(font_size=9, border_type=None, fill_pattern_type=None))
....
some coloring and formating
....
sf.to_excel(excel_writer=excel_writer, header=None, index=False, sheet_name="report")
excel_writer.save()
```
image/logo should be added to purple area starting from 1/4 cell
![image](https://user-images.githubusercontent.com/101246790/157405495-79edf36e-5d2f-4e99-9894-b66c23c2dd89.png)

Hope this helps

**Comment by DeepSpace2** [comment]
This can be done but with `openpyxl` as an engine (which will also require installation of `pillow`):

```python
import openpyxl

from styleframe import StyleFrame

sf = StyleFrame({'a': [1, 2, 3], 'b': [4, 5, 6]})
writer = StyleFrame.ExcelWriter('img_test.xlsx')
sf.to_excel(writer, index=False, header=None, sheet_name='Test').save()
worksheet = writer.sheets["Test"]
img = openpyxl.drawing.image.Image('fanart.jpg')
worksheet.add_image(img, anchor='D1')
writer.save()
```

Alternatively you can use the `xlsxwriter` method that you used but you will need to create a separate `pd.ExcelWriter` object (because `StyleFrame.ExcelWriter` only supports `openpyxl` as an engine)

**Comment by mitcharka** [comment]
Perfect, thank you.
Any way I can control image size without need to use PIL and resize it (and save it over original file or as new)?
I found this solution , but I guess its not optimal if I need to create/update image file every time

```
from PIL import Image

width = 23
height = 23
img = Image.open('photo.jpg')
img = img.resize((width,height),Image.NEAREST)
img.save('photo.jpg')

img = openpyxl.drawing.image.Image('photo.jpg')

```

**Comment by DeepSpace2** [comment]
This gets a bit out of scope of `StyleFrame`, but I believe you should be able to set `img.height` and `img.width`:

```python
...
worksheet = writer.sheets["Test"]
img = openpyxl.drawing.image.Image('logo.png')
img.height = 23
img.width = 23
worksheet.add_image(img, anchor='D1')
writer.save()
```

**Comment by mitcharka** [comment]
Thank you :)
