### ISSUE TITLE
Color row based on a criteria and export with style

### ISSUE THREAD

**Issue by SSMK-wq** [DeepSpace2/StyleFrame#121]
I have a sample dataframe like below

```
test_id,status,total,cnt_days,age     
1,passed,234%,3,21          
2,passed,54%,5,29
11,failed,21%,4,35
15,failed,20%.21,6,57             
51,passed,23%,21,80     
75,failed,12%,32,43

df1 = pd.read_clipboard(sep=',')
```

My objective is to 

a) Have dark border lines between rows and column using `black color`

b) Use `Green` color for header

c) Use `Red` color for rows where Total > 30%

d) convert the styled dataframe to a html object

e) Export the styled dataframe as is to .xlsx file (excel file)

So, with the help of this [post][1], I tried the below

    def highlight(row):
        if row['total'] > 30:
            return ['background-color: red'] * len(row)
        else:
            return [''] * len(row)

    s = data.style.apply(highlight, axis=1)
        #data['Total'] = data['Total'].astype(str) + "%"
        s = s.set_properties(
        **{'border': '1px black solid !important'}).set_table_styles([{
            'selector': '.col_heading',
            'props': 'background-color: green; color: black;'
        }])
        output = s.to_html(index=False)

But this produces incorrect output with gaps between different cells and borders. Another problem is my `Total` column has `%` symbol in it. How can I use that to do > 30% check and finally also display the `% symbol` in output table.

So, I expect my output to be like as below. you can see how there are no gap in borders between each cell and rows. I want the output to be like an excel table. Is there anyway to do this via StyleFrame? I also want to write the styled dataframe to an excel sheet with same format

![image](https://user-images.githubusercontent.com/30723825/169777732-ad0a1769-8aad-49db-b85e-2f41b087182f.png)

**Comment by DeepSpace2** [comment]
Styling HTML has never been in the scope of styleframe. However, styling the Excel file is straightforward if we keep in mind the percent column format. Here I'm using `iterrows` (which is usually not recommended because it is slow) but I'm sure there is a vectorized way to achieve the same:

```python
def find_indexes(sf):
    return [index.value for index, row in sf.iterrows()
            if float(row['total'].value.split('%')[0]) > 30]

sf.apply_headers_style(Styler(bg_color='green'))
sf.apply_style_by_indexes(find_indexes(sf), Styler(bg_color='red'))
sf.to_excel('test.xlsx').save()
```

**Comment by SSMK-wq** [comment]
@DeepSpace2 - Thanks for your help. Is it possible to convert sf to pandas dataframe?

**Comment by DeepSpace2** [comment]
The dataframe object is accessible through the `data_df` attribute.

**Comment by SSMK-wq** [comment]
but I get an error message that `AttributeError: 'StyleFrame' object has no attribute 'iterrows'` but I imported all the relevant packages from styleframe. You mean to say that iterrows() is slow or StyleFrame doesn't support `iterrows()`

**Comment by DeepSpace2** [comment]
Sorry, I fixed the example above. 
It should be 
```python
def find_indexes(sf):
    return [index.value for index, row in sf.data_df.iterrows()
            if float(row['total'].value.split('%')[0]) > 30]
```

**Comment by SSMK-wq** [comment]
I get an error `TypeError: 'NoneType' object is not iterable` when I try this on real dataframe. I unpacked the for loop for easy understandn=ing but not sure why it results in this error on real dataframe. Is it index issue?

```
def find_indexes(sf):
    for index, row in sf.data_df.iterrows():
        print("index is ", index)
        print("row is ", row)
        if float(row['BWin-POS Non-conversion measure'].value.split('%')[0]) > 30:
            return index
```

**Comment by DeepSpace2** [comment]
You are returning from inside the for loop, and you are also returning the index, not a list. This will causes the function to return `None` if no row matches the condition.
