### ISSUE TITLE
ValueError: Lightness must be between 0 and 1.

### ISSUE THREAD

**Issue by xRadne** [DeepSpace2/StyleFrame#124]
Python: 3.10.4
StyleFrame: 4.0.0
Pandas: 1.4.2
openpyxl: 3.0.10

### The error
Trying to read the following file gives the error. However if I change the background of cell A1 and A2, then it works, so the problem appears only for the color `Blue, Accent 5, Lighter 80%`.
![image](https://user-images.githubusercontent.com/32938476/173776542-5b305659-d6cd-480b-bcbd-5502bec8ffbc.png)

Test excel file: [test.zip](https://github.com/DeepSpace2/StyleFrame/files/8907159/test.zip)

Issue was previously raised in #65 but was closed.

**Comment by xRadne** [comment]
And I must say I love this wrapper around the pandas DataFrame! Good job!

**Comment by DeepSpace2** [comment]
Thanks for creating this issue and the warm words :)
#65 was closed because no input file was provided.

I did not completely implement the algorithm that calculates luminosity from tint, should be fixed in 4.1 that should already be available through `pypi`.

**Comment by xRadne** [comment]
Awesome! Very fast! 🚀
