### ISSUE TITLE
Contribution information's

### ISSUE THREAD

**Issue by Codeberg-AsGithubAlternative-buhtz** [DeepSpace2/StyleFrame#132]
There is no `CONTRIBUTE.md` file in the repo or any other information about how to contribute.

My question goes in the direction of your workflow? When creating a PR to which branch should I create it? `devel` or should I create my own branch in your repo e.g. `fix_xyz`? Do you have any naming conventions for branches?

Which branch should I "fork" (I hate that word)?

**Comment by DeepSpace2** [comment]
Hi, every contribution is welcomed :) 

There is no naming convention and you can create the PR into `devel`.

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
I would recommend to write these things down into a CONTRIBUTE.md or somewhere else.
I have some more questions in that context.

Somewhere in your commit messages I saw that you use flake8 and try to follow PEP8.

Do you have some specific modifications to PEP8 ore other code guidelines in your project?

For example flake8 gives me over 200 errors for `style_frame.py`. Most of them just because of lines longer then 80 chars (which is default).

Which rules do new contributors have to follow?
