### ISSUE TITLE
How to run unittests

### ISSUE THREAD

**Issue by Codeberg-AsGithubAlternative-buhtz** [DeepSpace2/StyleFrame#134]
I can run all unittests via discover feature.

`python3 -m unittest`

But I am not able to run specific tests classes or methods like this.

```
~/share/work/StyleFrame $ python3 -m unittest styleframe.tests.style_frame_tests.StyleFrameTest
E
======================================================================
ERROR: style_frame_tests (unittest.loader._FailedTest)
----------------------------------------------------------------------
AttributeError: module 'styleframe.tests.tests' has no attribute 'style_frame_tests'

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (errors=1)

```

How do you run specific parts of your test suite?

I am not very experienced with python project layout but I assume your layout is a bit unusual. ;) Not matter, this is not the time to make such a big change.

I just want to know how you do the things. ;)

Maybe related #132

**Comment by DeepSpace2** [comment]
To run a specific test class it is advisable to first CD into the `tests` directory then execute the specific class, for example:

```shell
styleframe\styleframe\tests $ python3 -m unittest style_frame_tests.StyleFrameTest
```

To run a specific test from that class:

```shell
styleframe\styleframe\tests $ python3 -m unittest style_frame_tests.StyleFrameTest.test_init_styler_obj
```

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
I assume that is just the half of what is needed.
I `cd`'d into `/home/user/share/work/StyleFrame/styleframe/tests` and then tried

```
$ python3 -m unittest style_frame_tests.StyleFrameTest
E
======================================================================
ERROR: style_frame_tests (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: style_frame_tests
Traceback (most recent call last):
  File "/usr/lib/python3.9/unittest/loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
  File "/home/user/share/work/StyleFrame/styleframe/tests/style_frame_tests.py", line 12, in <module>
    from styleframe import Container, StyleFrame, Styler, utils
ModuleNotFoundError: No module named 'styleframe'


----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (errors=1)

```

What is different in your environment. You installed `styleframe` that it can be imported from everywhere in your system right?

For cases like this I use the `--editable` option of `pip`. Just want to know if you do it the same way?

Back to project root:
```

python3 -m pip install --editable .
Defaulting to user installation because normal site-packages is not writeable
Obtaining file:///home/user/share/work/StyleFrame
  Preparing metadata (setup.py) ... done
Requirement already satisfied: openpyxl<4,>=2.5 in /usr/lib/python3/dist-packages (from styleframe==4.1) (3.0.3)
Requirement already satisfied: colour<0.2,>=0.1.5 in /usr/local/lib/python3.9/dist-packages (from styleframe==4.1) (0.1.5)
Requirement already satisfied: jsonschema in /usr/lib/python3/dist-packages (from styleframe==4.1) (3.2.0)
Requirement already satisfied: pandas<2 in /usr/local/lib/python3.9/dist-packages (from styleframe==4.1) (1.3.0)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/lib/python3/dist-packages (from pandas<2->styleframe==4.1) (2.8.1)
Requirement already satisfied: numpy>=1.17.3 in /usr/lib/python3/dist-packages (from pandas<2->styleframe==4.1) (1.19.5)
Requirement already satisfied: pytz>=2017.3 in /usr/lib/python3/dist-packages (from pandas<2->styleframe==4.1) (2021.1)
Installing collected packages: styleframe
  Running setup.py develop for styleframe
Successfully installed styleframe
WARNING: There was an error checking the latest version of pip.

```

Now the unittests are workin.

But things like this need to be written down somewhere for other contributors. I will prepare a `CONTRIBUTE.md` if it is OK for you. Especially the `--editable` option is unknown to lot of inexperienced python users.

But please let me know if you do it another way. For example I don't use python environments.

**Comment by DeepSpace2** [comment]
> What is different in your environment. You installed `styleframe` that it can be imported from everywhere in your system right?
> 
> For cases like this I use the `--editable` option of `pip`. Just want to know if you do it the same way?

Well, you are actually correct. I must have done this ages ago as I had an old version of styleframe installed within the virtual environment. 

Installing in editable mode does seem to be the easier workaround, rather than debugging why `unittest discover` works but running a specific test case fails (I assume it has something to do with how `unittest discover` works internally, ie it might `sys.path.append`  every directory it finds). 

>  I will prepare a CONTRIBUTE.md if it is OK for you

Of course! Go ahead if you want to :). There is already a `.github/CONTRIBUTING.md` you can edit.

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
> There is already a `.github/CONTRIBUTING.md` you can edit.

I have never seen a `.github` subfolder and that files in it. What is this for? The usual users are not able to read this. No one will enter a dot-folder. ;) Is there a GitHub feature behind? Are this files linked somewhere into the GitHub web-frontend?

**Comment by DeepSpace2** [comment]
Placing these files inside the `.github` is just a convention. From GitHub's [Setting guidelines for repository contributors documentation](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors):

> To help your project contributors do good work, you can add a file with contribution guidelines to your project repository's root, `docs`, or `.github` folder
