### ISSUE TITLE
Test environment with `python3.10-dev` not working

### ISSUE THREAD

**Issue by Codeberg-AsGithubAlternative-buhtz** [DeepSpace2/StyleFrame#140]
I never worked with CI or the GitHub backend doing automated tested.
I only can see that there is a problem setting up the `python3.10-dev` environment.

Any idea how to fix that or where we can ask questions like this?
I am not aware of any GitHub support forum when you don't pay for that.

**Comment by DeepSpace2** [comment]
There is an issue with installing dependencies on the Python 3.10-dev branches of Python and I never got the chance to use the GA version of Python 3.10 in the CI when it became publicly available.

I just pushed a new CI file to the devel branch.
