### ISSUE TITLE
Challenges with date formatting

### ISSUE THREAD

**Issue by dphaine** [DeepSpace2/StyleFrame#145]
Hi there!  Thanks for this great package!

I'm having much trouble coaxing dates into the needed format.

Based on the code here: https://github.com/DeepSpace2/StyleFrame#advance-example I have this:
```
from datetime import date
from styleframe import StyleFrame, Styler, utils
ew = StyleFrame.ExcelWriter("220930 StyleFrame Date Test.xlsx")
dateList = [date(2016, 10, 20), date(2016, 10, 21), date(2016, 10, 22)]
sf = StyleFrame(
    {"Dates": dateList},
    styler_obj=Styler(number_format="MM/DD/YYYY", bold=True),
)
sf.to_excel(excel_writer=ew)
ew.save()
```
However it's coming out in a different format (DD/MM/YY).
<img width="251" alt="image" src="https://user-images.githubusercontent.com/8638184/193330585-3bcdc0af-795f-4d35-bbcc-7a6a4e74c0bc.png">

This seems related to:
https://github.com/DeepSpace2/StyleFrame/issues/90

Any ideas for me?  Thank you!

Versions:
Python 3.10
styleframe 4.1
pandas 1.5.0
openpyxl 3.0.10

**Comment by DeepSpace2** [comment]
Hi. The date format should be passed as `date_format`, not `number_format`.

**Comment by dphaine** [comment]
Ah thank you very much!!  I saw the date formats listed under "number_formats" in [the docs](https://styleframe.readthedocs.io/en/latest/utils.html) leading to my mistake:

<img width="387" alt="image" src="https://user-images.githubusercontent.com/8638184/193359894-4e8565e9-ace7-4821-89ae-1c06ea0441ab.png">

**Comment by dphaine** [comment]
Ah I also saw this reference in [the readme](https://github.com/DeepSpace2/StyleFrame) that looks like a mistake.
<img width="840" alt="image" src="https://user-images.githubusercontent.com/8638184/193360974-d084081b-a9a0-4a7b-9255-a7b61e6bc7bf.png">

**Comment by DeepSpace2** [comment]
Thanks for pointing this out. This piece of the readme is pretty old, I guess it is time for a small update. Thanks 👍

**Comment by DeepSpace2** [comment]
[`ExcalWriter.save` is being deprecated by pandas](https://pandas.pydata.org/docs/reference/api/pandas.ExcelWriter.save.html), and [`ExcelWriter.close`](https://pandas.pydata.org/docs/reference/api/pandas.ExcelWriter.close.html) should be used instead.
