### ISSUE TITLE
help

### ISSUE THREAD

**Issue by forvendettaw** [DeepSpace2/StyleFrame#22]
Hi! Thanks for contributing to StyleFrame. 
 I create pandas dataframe with hdfs data,and write to excel,
and i encounter a problem,
i can't formate excel columns ,
and i can't find answer in source code.
but there is a NumberFormatDescriptor class in openpyxl , and styleframe have not.

My expectation is that：

5.42237E+11  convert to  542236815955  in excel

thank you .Forgive me  a freshman .

**Comment by DeepSpace2** [comment]
Hi. What would the expected output be? Both StyleFrame (0.2) and "plain" pandas (0.18.1) provide the same output which as follows:

![untitled](https://cloud.githubusercontent.com/assets/6841988/22019155/f9fb3014-dcba-11e6-82a8-172c3357d0cd.png)

**Comment by forvendettaw** [comment]
That's what I expected

![image](https://cloud.githubusercontent.com/assets/24313853/22060261/0a8c7e10-ddab-11e6-8f51-fa4979b80fa5.png)

thank you again

**Comment by forvendettaw** [comment]
but now it's like this;

![image](https://cloud.githubusercontent.com/assets/24313853/22060338/4b51d058-ddab-11e6-80ec-b3130db9f48b.png)

**Comment by DeepSpace2** [comment]
All you need to do is use `'0'` for `number_format`. In future versions I'll add it to one of the preset formats in `utils.number_formats`.

    sf = StyleFrame({'a':[5.42237E+11]})
    sf.apply_column_style(cols_to_style='a', styler_obj=Styler(number_format='0'))
