### ISSUE TITLE
Pandas 0.23.1 Support

### ISSUE THREAD

**Issue by harriv** [DeepSpace2/StyleFrame#36]
Is there any changes required to support latest Pandas 0.23.1?

**Comment by DeepSpace2** [comment]
<strike>Probably</strike> Hopefully not. 

For now you can try it by first installing `StyleFrame` and then updating `pandas`. 

You can make sure everything is working as expected by running the tests:

```python
from StyleFrame import tests

tests.run()
```

If everything works out we can update the `pandas` version in `setup.py` and `requirement.txt`.

**Comment by DeepSpace2** [comment]
Probably no, as the latest [travis build](https://travis-ci.org/DeepSpace2/StyleFrame/jobs/389709649) was tested against `pandas` 0.23.0 so I expect everything to work

For now you can try it by first installing `StyleFrame` and then updating `pandas`. 

You can make sure everything is working as expected by running the tests:

```python
from StyleFrame import tests

tests.run()
```

If everything works we can update the `pandas` version in `setup.py` and `requirement.txt`.

**Comment by harriv** [comment]
Seems to work, few warnings came up:
```

.....C:\Users\Harriv\AppData\Local\Programs\Python\Python36\lib\site-packages\
openpyxl\styles\styleable.py:111: UserWarning:Use formatting objects such as fon
t directly
...........C:\Users\Harriv\AppData\Local\Programs\Python\Python36\lib\site-pac
kages\pandas\io\excel.py:329: FutureWarning:The `sheetname` keyword is deprecate
d, use `sheet_name` instead
.C:\Users\Harriv\AppData\Local\Programs\Python\Python36\lib\site-packages\open
pyxl\workbook\names\named_range.py:121: UserWarning:Discarded range with reserve
d name
.............
```

**Comment by DeepSpace2** [comment]
version 1.6 will support pandas <= 0.23.1
