### ISSUE TITLE
Newer openpyxl support

### ISSUE THREAD

**Issue by patarapolw** [DeepSpace2/StyleFrame#40]
I use poetry to help this, and finally I get it resolved, but admittedly, quite problematic...

    pyexcel = "^0.5.8"
    pyexcel-xlsx = "^0.3.0"
    openpyxl = "<=2.2.5"
    styleFrame = "^1.6"
    pandas = "<=0.23.1"

on Mac OS X.

**Comment by DeepSpace2** [comment]
Hi.
I'm not sure what do you mean. Are you referring to the fact that StyleFrame requires openpyxl <= 2.2.5?

**Comment by patarapolw** [comment]
Yes. But as I installed pyexcel, pyexcel-xlsx first, it prevents me from installing styleFrame directly...

**Comment by DeepSpace2** [comment]
openpyxl's API has significantly changed. Supporting later versions of it is on the roadmap, just not sure when exactly it would happen.

**Comment by patarapolw** [comment]
Actually, it's about `pandas` as well. poetry will always attempt to install the newest version.

**Comment by DeepSpace2** [comment]
Closed by 588065a2b0d98272e2e871ce17f84bd4c1bf9d56
