### ISSUE TITLE
read_style=True keep column width and wrap text

### ISSUE THREAD

**Issue by kristiansvenssonwsp** [DeepSpace2/StyleFrame#41]
Hi!

Using `StyleFrame.read_excel(spreadsheet, read_style=True)`, is it possible to keep column widths and wrap_text from the orginal excel-file when writing a new excel file?

openpyxl = 2.2.5
pandas = 0.23.1
python = 3.6.6 64 bit
StyleFrame = 1.6

**Comment by DeepSpace2** [comment]
Hi.
`wrap_text` is already loaded correctly. I'll add columns widths and rows heights in the next version.

**Comment by DeepSpace2** [comment]
1.6.1 is available.
