### ISSUE TITLE
Default Border option

### ISSUE THREAD

**Issue by N2ITN** [DeepSpace2/StyleFrame#42]
Is there a way to have the default Excel borders around cells?
Setting `Styler(border_type=None)` will eliminate borders around cells, but I want the default background grid.

**Comment by DeepSpace2** [comment]
This is a(n unfortunate) side-effect of Styler Defaulting to white background ("Fill" in Excel terminology).
The workaround is to set `fill_patern_type=None` when using a borderless style:

`Styler(border_type=None, fill_pattern_type=None)`

**Comment by N2ITN** [comment]
Thank you!

**Comment by DeepSpace2** [comment]
In version 3 there will be a shortcut to achieve this. `Styler(border_type=utils.borders.default_excel_grid)` will be the equivallent for  `Styler(border_type=None, fill_pattern_type=None)`.
