### ISSUE TITLE
fails to install

### ISSUE THREAD

**Issue by zenzugr** [DeepSpace2/StyleFrame#51]
Hi! Thanks for contributing to StyleFrame. Please make sure to mention the Python, StyleFrame, pandas and openpyxl versions you are using.

[build_error_log_styleframe.txt](https://github.com/DeepSpace2/StyleFrame/files/2753573/build_error_log_styleframe.txt)
pandas 0.23.0
python 3.7.0
openpyxl 2.5.3
Tried numerous times to install with "pip install styleframe".  Please see the error log.

**Comment by DeepSpace2** [comment]
Hi.
Please note that this error comes from `numpy`, not `styleframe`. Consult [this `numpy` issue](https://github.com/numpy/numpy/issues/9895).
