### ISSUE TITLE
Packaging: Cannot execute setup.py without dependencies installed

### ISSUE THREAD

**Issue by rbu** [DeepSpace2/StyleFrame#54]
The ```setup.py``` does not allow bootstrapping the project, as it requires the package dependencies to be installed (while at the same time, it is used to define the dependencies).

## Reason:
The file determines the package version by importing the package (specifically, ```StyleFrame.version```), which requires the dependencies to be installed.

## Steps to reproduce:
1. ```python3 -m venv tmp```
2. ```source tmp/bin/activate```
3. ```git clone https://github.com/DeepSpace2/StyleFrame```
4. ```cd StyleFrame```
5. ```pip install -e .```

## Expected results:
* StyleFrame installs

## Actual results:
```
Obtaining StyleFrame
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/StyleFrame/setup.py", line 2, in <module>
        from StyleFrame.version import _version_
      File "/StyleFrame/StyleFrame/__init__.py", line 3, in <module>
        from .container import Container
      File "/StyleFrame/StyleFrame/container.py", line 4, in <module>
        import pandas as pd
    ModuleNotFoundError: No module named 'pandas'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in StyleFrame/
```

## Solution:
There are several good ideas to have a single source of truth for the package version discussed in the Python Packaging Guide: https://packaging.python.org/guides/single-sourcing-package-version/

CC @nnfuzzy

**Comment by DeepSpace2** [comment]
Related to #53.
I'm pretty sure this only happens when trying to install from source, as I could not reproduce it in any other way (including docker and pipenv)

**Comment by rbu** [comment]
> I reproduced steps 1 and 2 then, instead of cloning and executing `pip install -e .` I did `pip install StyleFrame` and it works:

Correct, however still a blocker for new developers (or yourself, if you lose the existing virtualenv).

**Comment by DeepSpace2** [comment]
@rbu fair enough. I'll merge #53 into [devel](/github/DeepSpace2/tree/devel)
