### ISSUE TITLE
xlrd Version ImportError

### ISSUE THREAD

**Issue by richkamulda** [DeepSpace2/StyleFrame#58]
Pandas version is 0.25.2 with StyleFrame 2.0.4 and openpyxl 3.0.0; on pd.ExcelFile(), I receive an ImportError for xlrd. "Pandas requires version '1.1.0' or newer of 'xlrd' (version '1.0.0' currently installed)." StyleFrame is only bringing in 1.0.0 which is not compatible with newer versions of pandas.

**Comment by DeepSpace2** [comment]
Hi, this is solved in version 2.0.5 which requires `xlrd >= 1.0.0` instead of `xlrad == 1.0.0`
