### ISSUE TITLE
Potential to integrate code-base with xl_link

### ISSUE THREAD

**Issue by 0Hughman0** [DeepSpace2/StyleFrame#60]
Hi,

This almost certainly isn't the best way to approach you, but I couldn't find an email address.

A few years ago I wrote a library called xl_link: https://github.com/0Hughman0/xl_link

The idea is that after you write a DataFrame to a spreadsheet, xl_link provides a 'map' that is basically like a mirror of your original DataFrame, except rather than storing data, it stores _where_ that data was written to the spreadsheet.

I'm extremely busy at the moment, and I don't really have the time to maintain the program. It still broadly works, just with a few little edge-cases popping up errors. 

Having started writing some Excel related code recently, I was looking to find ways to format DataFrames in Excel and your library popped up. It looks to me that aims of StyleFrame might be very well complemented by xl_link. 

I'm wondering if there would be a way to integrate the 2 libraries. This is mostly speculation, and no pressure - I probably wouldn't have time to help much at all I'm afraid, but rather than let xl_link die out, I thought it might be nice if it's spirit could live on by getting sucked up by a bigger project - I'm still very proud of its functionality!

Cheers,

Hugh

**Comment by DeepSpace2** [comment]
Hi. Sorry for the late reply.

I like the way you are supporting charts (which to be honest I was too lazy to implement 😁).

How do you envision the usage of the XLMapping object once the StyleFrame object is created?
