### ISSUE TITLE
AttributeError: 'numpy.ndarray' object has no attribute 'style'

### ISSUE THREAD

**Issue by pajachiet** [DeepSpace2/StyleFrame#61]
Thanks for your work

- Python 3.7.3
- StyleFrame 2.0.5
- pandas 0.25.3
- openpyxl 3.0.2

I want to read an xlsx file as described in this [SO answer](https://stackoverflow.com/questions/44861989/reading-an-excel-with-pandas-basing-on-columns-colors), but I get the following error

**Code**
``` python
sf = StyleFrame.read_excel(file_path, 
                           sheet_name=1,
                           index_col=0, 
                           read_style=True
                          )
```

**Error**
```
lib/python3.7/site-packages/StyleFrame/style_frame.py in _read_style()
    208                         style_object = Styler.from_openpyxl_style(current_cell, theme_colors,
    209                                                                   read_comments and current_cell.comment)
--> 210                     sf.at[sf_index, col_name].style = style_object
    211                     sf._rows_height[row_index] = sheet.row_dimensions[row_index].height
    212 

AttributeError: 'numpy.ndarray' object has no attribute 'style'
```

Do you I make a mistake somewhere or is there a bug ?

**Comment by pajachiet** [comment]
Reading the code, I understood that the issue is caused by `index_col=0`.
I managed to get arround the problem for myself by removing this argument.

**Comment by pajachiet** [comment]
Did you manage to fix the bug or improve the documentation ?

**Comment by MattMacs** [comment]
Please re-open, the issue remains...

-     Python 3.8.2
-     StyleFrame 2.0.5
-     pandas 1.0.3
-     openpyxl 3.0.3

Trying to save a dataframe
`sf = StyleFrame(dataframe)
 sf.to_excel()`

**Comment by DeepSpace2** [comment]
@MattMacs  Please a full code that can reproduce this issue.

**Comment by MattMacs** [comment]
Hi, got it resolved, used df.set_index before. 

After removing it, everything works smoothly.
