### ISSUE TITLE
Why not show the index when I save sf to excel?

### ISSUE THREAD

**Issue by dilless** [DeepSpace2/StyleFrame#62]
- Python == 3.7
- StyleFrame == 2.0.5
- pandas == 0.25.3
- openpyxl == 3.0.2

My code shows below, I tried to save sf to excel file, but lost the index in excel.
```python
ew = StyleFrame.ExcelWriter(filepath + '/' + filename + '-result' + extension)
sf.to_excel(ew, best_fit=sf.columns.to_list())
ew.save()
````
THX

**Comment by DeepSpace2** [comment]
The index will be shown if `index=True` is passed to `to_excel`:

    sf.to_excel(ew, best_fit=sf.columns.to_list(), index=True)

**Comment by TimurDela** [comment]
This information is missing from the API documentation.

Is there any way to make it work for multi indexes?

**Comment by DeepSpace2** [comment]
@TimurDela Hi, the [documentation for `StyleFrame.to_excel`](https://styleframe.readthedocs.io/en/latest/api_documentation.html#styleframe.StyleFrame.to_excel) mentions 

> to_excel also accepts all arguments that pandas.DataFrame.to_excel accepts as kwargs

As per your question, no. `styleframe` does not support multi-index at the moment. The index of the dataframe will be "squashed" by https://github.com/DeepSpace2/StyleFrame/blob/da61d6294c952fb4ac8d5ecf3c503322b244ac0f/styleframe/style_frame.py#L58-L59
