### ISSUE TITLE
Suggestion :  Supporting PyExcelerate

### ISSUE THREAD

**Issue by anubhav1** [DeepSpace2/StyleFrame#63]
Styleframe is not compatible with PyExcelerate. Please check out the [issue ](https://github.com/kz26/PyExcelerate/issues/87) on PyExcelerate. It would be awesome if PyExcelerate is supported because saving a formatted excel takes lot of time.

**Comment by DeepSpace2** [comment]
Hi. I replied on https://github.com/kz26/PyExcelerate/issues/87

**Comment by anubhav1** [comment]
Great!! Hopefully there will be a solution.
