### ISSUE TITLE
Is it possible to set a border for a single side?

### ISSUE THREAD

**Issue by mjozan** [DeepSpace2/StyleFrame#66]
Hello,

I would like to know if it is possible to set the border for a single side with this library like border-bottom, or border-top?

Thank you for your answer.

**Comment by DeepSpace2** [comment]
Hi, not at the moment, but it will be in a future release.

**Comment by jnothman** [comment]
Is it useful to have an API like `add_border_before_columns(["A", "B", "D")`? I have also wondered about automatically 
inserting borders to correspond with upper levels of a MultiIndex.

**Comment by DeepSpace2** [comment]
@jnothman I actually did start to develop an API for this on [dedicated branch] (https://github.com/DeepSpace2/StyleFrame/compare/individual-borders-control) (more than a year ago, I know 😔).

It's quite different than your suggestion but it got the job done, however I never got to finish it.

**Comment by DeepSpace2** [comment]
@jnothman Better late than never I guess :) 

I restarted work on this feature, if you still care about it you can follow the discussion [here](https://github.com/DeepSpace2/StyleFrame/commit/42d37382d4f317fc872bb358171186c34b9e05f6)

**Comment by DeepSpace2** [comment]
Done, this is part of the future 4.2 release.
