### ISSUE TITLE
‘use_openpyxl_styles’ in ‘read_excel’ makes ‘to_excel’ back fail

### ISSUE THREAD

**Issue by mjozan** [DeepSpace2/StyleFrame#67]
Python version : 3.7.5
Openpyxl : 3.0.3
Pandas : 1.0.3
StyleFrame : 2.0.5

Hello

I am trying to read the style of a really simple excel and save it back to another excel with this code (the error only happens when setting `use_openpyxl_styles` to `True`:

```
tests_dir = os.path.dirname(__file__)
TEST_FILENAME = os.path.join(tests_dir, 'Book10.xlsx')
TEST_FILENAME2 = os.path.join(tests_dir, 'Book11.xlsx')
sf_from_excel = StyleFrame.StyleFrame.read_excel(TEST_FILENAME, read_style=True, sheet_name='Sheet1', use_openpyxl_styles=True)
ew = StyleFrame.StyleFrame.ExcelWriter(TEST_FILENAME2)
sf_from_excel.to_excel(ew)
ew.save()
 ```

However, I get this error:
```
Traceback (most recent call last):
  File “test.py", line 20, in <module>
    test()
  File "test.py.py", line 16, in test
    sf_from_excel.to_excel(ew)
  File "/Users/homefolder/Documents/teststyle/StyleFrame/StyleFrame/style_frame.py", line 359, in to_excel
    column_header_cell.style = style_to_apply
  File "/Users/homefolder/Documents/teststyle/StyleFrame/styleframeenv/lib/python3.7/site-packages/openpyxl/styles/styleable.py", line 85, in __set__
    raise ValueError("{0} is not a known style".format(value))
ValueError: <Cell 'Sheet1'.A1> is not a known style
```

The value <Cell 'Sheet1'.A1> when reading is set here:

https://github.com/DeepSpace2/StyleFrame/blob/dc9653043156495b973ccbb6406d1a6554b579aa/StyleFrame/style_frame.py#L196-L197

And the error when writing happens here : 
https://github.com/DeepSpace2/StyleFrame/blob/dc9653043156495b973ccbb6406d1a6554b579aa/StyleFrame/style_frame.py#L354-L357

The error is originally raised here : 

https://github.com/ArthurWatier/top_affinite/blob/36286aa256b283166382dd4c1041bc6e3775e781/venv/lib/python3.5/site-packages/openpyxl/styles/styleable.py#L81

Could you help me solve this error please? Thank you for your answer.

**Comment by DeepSpace2** [comment]
Thanks for reporting, this will be fixed in the next  release
