### ISSUE TITLE
Doesn't work with pathlib path

### ISSUE THREAD

**Issue by impredicative** [DeepSpace2/StyleFrame#69]
```bash
$ python -V
Python 3.8.1
```

```bash
$ pip list | egrep -i 'openpyxl|pandas|styleframe'
openpyxl          3.0.3
pandas            1.0.4
StyleFrame        2.0.5
```

`StyleFrame(df).to_excel('/tmp/foo.xlsx', index=True).save()` works, but 
`StyleFrame(df).to_excel(pathlib.Path('/tmp/foo.xlsx'), index=True).save()` raises `AttributeError: 'PosixPath' object has no attribute 'sheets'`. It is reasonable to expect pathlib paths to also work, as they do with Pandas.

**Comment by DeepSpace2** [comment]
Thanks, will be fixed in the next release.
