### ISSUE TITLE
Calling color definitions which are removed in latest openpyxl (3.0.4)

### ISSUE THREAD

**Issue by emacholdt** [DeepSpace2/StyleFrame#73]
Hi, I just encountered an issue with styleframe-3.0.4 when importing StyleFrame. 
I am running Python 3.6 in a docker with Pandas 0.25.3

From what I have figured out, my previous deplyment with openpyxl 3.0.3 worked fine. But during a new docker build openpyxl 3.0.4 was choosen as a dependency for styleframe and it cause the following error:

```
Traceback (most recent call last):
File "./main.py", line 13, in <module>
...
from styleframe import StyleFrame
File "/usr/local/lib/python3.6/site-packages/styleframe/__init__.py", line 3, in <module> 
 from .container import Container
File "/usr/local/lib/python3.6/site-packages/styleframe/container.py", line 4, in <module>
 from . import utils
File "/usr/local/lib/python3.6/site-packages/styleframe/utils.py", line 42, in <module> 
 class colors(BaseDefClass):
File "/usr/local/lib/python3.6/site-packages/styleframe/utils.py", line 45, in colors
 dark_blue = op_colors.DARKBLUE
AttributeError: module 'openpyxl.styles.colors' has no attribute 'DARKBLUE'
unable to load app 0 (mountpoint='') (callable not found or import error) 
```

Manually installing an earlier version of openpyxl (3.0.1) is my current workaround.

From my understanding, it happens due to this change https://bitbucket.org/openpyxl/openpyxl/commits/31cb130dd3b9a856b2fc3d8c1183d77e4cab51f1

**Comment by DeepSpace2** [comment]
Thanks for the update.

As a quick fix, I will release soon a hotfix version of styleframe that pins openpyxl version to <= 3.0.3. 

Later, I will change styleframe so it no longer depends on openpyxl's colors defs.

**Comment by DeepSpace2** [comment]
styleframe 3.0.2 is released

**Comment by sks444** [comment]
>As a quick fix, I will release soon a hotfix version of styleframe that pins openpyxl version to <= 3.0.3.

Hey @DeepSpace2 , I think you missed the `=` part when setting version requirements for oepnpyxl, it is now `openpyxl>=2.5,<3.0.3` which currently installs openpyxl version `3.0.2` which causes following error when writing to excel:
```
TypeError: got invalid input value of type <class 'xml.etree.ElementTree.Element'>, expected string or Element
```
[Which is fixed in openpyxl 3.0.3.](https://stackoverflow.com/questions/59168758/the-function-to-excel-of-pandas-generate-an-unexpected-typeerror)

**Comment by DeepSpace2** [comment]
@sks444 Thanks for making me aware, however I'm a bit surprised you are getting this error (as the travis builds are passing with `openpyxl-3.0.2` - https://travis-ci.com/github/DeepSpace2/StyleFrame/jobs/356375508#L194).

Maybe this bug only happens with `openpyxl-3.0.2` and a specific `pandas` version?

**Comment by huruka** [comment]
Also have TypeError when use to_excel()
install openpyxl==3.0.3 correct
my pandas version 1.0.3

**Comment by DeepSpace2** [comment]
@huruka Hi. This issue is about a very specific `AttributeError`. Please open a new issue about your `TypeError` and provide the full traceback + how to reproduce it if possible.

**Comment by answerquest** [comment]
Here's the relevant documentation page in openpyxl: https://openpyxl.readthedocs.io/en/stable/_modules/openpyxl/styles/colors.html 

There's another incompatibility of pandas library's to_excel() with lower versions of openpyxl. I bumped it up and then found that styleframe has **this** problem with the higher versions! Please fix this soon. Just replace `DARKBLUE` with the appropriate `COLOR_INDEX[n]` .

**Comment by DeepSpace2** [comment]
3.0.3 is released, these issues should be gone
