### ISSUE TITLE
AttributeError: 'numpy.ndarray' object has no attribute 'style'

### ISSUE THREAD

**Issue by ferdelcorro** [DeepSpace2/StyleFrame#75]
Hi! Thanks for contributing to StyleFrame. Please make sure to mention the Python, StyleFrame, pandas and openpyxl versions you are using.

I leave you a small problem that I found, I do not know if it is a bug or if the parameters are wrong, but surely someone else will have the same problem.

python 3.6
styleframe 3.0.2
pandas 1.0.5
openpyxl 3.0.3

i'm reading some csv from google cloud storage, generating a dataframe from every file and after that concat all in one.
I pass this big dataframe to StyleFrame and apply it some styles but when i tray to export it to excel it give an error
```
File "xxxxx/python3.6/site-packages/styleframe/style_frame.py", line 414, in to_excel
    data_df_style = self.data_df.at[index, column].style
AttributeError: 'numpy.ndarray' object has no attribute 'style
```

Then i started to debug the code and when i want to display the line 414 (styleframe/style_frame.py) i saw 
```
[<styleframe.container.Container object at 0x7f4e4a141048>
 <styleframe.container.Container object at 0x7f4e4a141ef0>
 <styleframe.container.Container object at 0x7f4e4a141a58>
 <styleframe.container.Container object at 0x7f4e4a1416a0>
 <styleframe.container.Container object at 0x7f4e4a1b2898>
 <styleframe.container.Container object at 0x7f4e4a1b2908>
 <styleframe.container.Container object at 0x7f4e4a1b2dd8>]
```

My workaround was export the df to csv without use   StyleFrame and read it again, this time with StyleFrame and styles, then code works perfectly.

```
df = pd.concat(dataframes)
df.to_csv("combined_csv.csv", index=False, encoding='utf-8')
df = pd.read_csv("combined_csv.csv")

# Define styles
default_style = Styler(
    font_size=10,
    horizontal_alignment=utils.horizontal_alignments.center,
    vertical_alignment=utils.vertical_alignments.center)
header_styler = Styler(
    font_size=10,
    bold=True,
    bg_color='#7030a0',
    font_color=utils.colors.white)
header_style = Styler(bold=True, font_size=18)

# Setup StyleFrame
sf = StyleFrame(df, styler_obj=default_style)
sf.apply_headers_style(styler_obj=header_styler)

# Change the columns width and the rows height
sf.set_column_width(columns=sf.columns, width=20)
sf.set_row_height(rows=sf.row_indexes, height=20)

# Save excel
sf.to_excel('{}.xlsx'.format(TODAY)).save()
```

**Comment by DeepSpace2** [comment]
Hi.
Can you please show the code that doesn't work (or a similar code that causes the same error)?

Thanks.

**Comment by ferdelcorro** [comment]
This is a basic example

```
import pandas as pd
from styleframe import StyleFrame, Styler, utils   
   
df1 = pd.DataFrame(
    {'Time': [1.496728e+09, 1.496728e+09, 1.496728e+09, 1.496728e+09, 1.496728e+09]},
    columns=['Time'])

df2 = pd.DataFrame({
    {'Time': [1.496728e+09, 1.496728e+09, 1.496728e+09, 1.496728e+09, 1.496728e+09]},
    columns=['Time'])

dataframes = [df1, df2]
df = pd.concat(dataframes)
default_style = Styler(font=utils.fonts.aharoni, font_size=14)
sf = StyleFrame(df, styler_obj=default_style)
sf.to_excel('output.xlsx', index=False).save()
```

and in shell i've the error 

```
>>> sf.to_excel('output.xlsx', index=False).save()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "xxxxx/python3.6/site-packages/styleframe/style_frame.py", line 413, in to_excel
    data_df_style = self.data_df.at[index, column].style
AttributeError: 'numpy.ndarray' object has no attribute 'style'
```

**Comment by DeepSpace2** [comment]
Thanks. For unknown reasons the culprit seems to be the usage of pd.concat. I'll investegate more later.

**Comment by DeepSpace2** [comment]
@ferdelcorro Ok, so `pd.concat` uses the indexes of the original dataframes. In your case both the dataframes have the default numeric indexes (from `0` to `len_of_df - 1`) which causes the merged dataframe to contain duplicated indexes:

```
                   Time
0  1.496728e+09
1  1.496728e+09
2  1.496728e+09
3  1.496728e+09
4  1.496728e+09
0  1.496728e+09
1  1.496728e+09
2  1.496728e+09
3  1.496728e+09
4  1.496728e+09
```

which in turn causes `self.data_df.at[index, column]` to return a `numpy.ndarray` instead of a series which styleframe expected.

I haven't decided yet if (and if so, how) this should be handled within styleframe, but in the meanwhile the most straightforward way to solve this is to use `.reset_index()` before instantiating `StyleFrame`:

```
df1 = pd.DataFrame({'Time': [1.496728e+09, 1.496728e+09, 1.496728e+09, 1.496728e+09, 1.496728e+09]},columns=['Time'])
df2 = pd.DataFrame({'Time': [1.496728e+09, 1.496728e+09, 1.496728e+09, 1.496728e+09, 1.496728e+09]},columns = ['Time'])
dataframes = [df1, df2]
df = pd.concat(dataframes).reset_index()
default_style = Styler(font=utils.fonts.aharoni, font_size=14)
sf = StyleFrame(df, styler_obj=default_style)
sf.to_excel('output.xlsx', index=False).save()
```

**Comment by DeepSpace2** [comment]
@xRadne  This line `df.at[ind, ["B", "C"]] = [500, 600]` breaks `styleframe` since it's assigning an `int` as the content of the dataframe "cell" instead of the expected `styleframe.Styler` object (hence the `AttributeError: 'int' object has no attribute 'style'` error).

As a rule of thumb, it is best to do all data-mangling before creating the `StyleFrame` object, though I understand that in this case it is not possible since you want to keep the styling of the existing sheet.

A workaround would be to use a `StyleFrame.Container` with the style we get from the sheet:

```python
from styleframe import StyleFrame, Container

sf = StyleFrame.read_excel('test.xlsx', read_style=True)
sf.at[0, 'A'] = Container("new_value", sf.at[0, 'A'].style)
sf.to_excel('updated.xlsx').save()
```
