### ISSUE TITLE
StyleFrame does not recognize bold cells in .xlsx file

### ISSUE THREAD

**Issue by Marmeladenbrot** [DeepSpace2/StyleFrame#80]
I have a file where I want to get all bold cells for column A.
I made a test file (https://www.dropbox.com/s/vi625tn9wrw4940/test.xlsx?dl=0).

Code:

```
from styleframe import StyleFrame
sf = StyleFrame.read_excel("test.xlsx", read_style=True, use_openpyxl_styles=False, header=None, usecols="A")

for row in sf[0]:
    if row.style.bold:
        print(row)
```

Which should result in: A2, A5, A10
But I get: A1, A4, nan

How can I get cells which are bold for column A?

**Comment by DeepSpace2** [comment]
The usage of `header=None` caused the styles to "shift". Fixed in version 3.0.4 which is already on `pypi`.
