### ISSUE TITLE
Importing styleframe throws a deprecation error.

### ISSUE THREAD

**Issue by helios210** [DeepSpace2/StyleFrame#84]
Importing styleframe v3.0.5 causes "DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future." on all cells in Jupyter notebook.

Python: v3.8.5
StyleFrame: v3.0.5
Pandas: v1.1.1
Openpyxl: v3.0.4

**Comment by DeepSpace2** [comment]
Hi. 

This message apparently does not come from styleframe (or even any of it dependencies), but from Jupyter itself.
See https://stackoverflow.com/questions/63413807/deprecation-warning-from-jupyter-should-run-async-will-not-call-transform-c

**Comment by helios210** [comment]
Hi Adi,

Yes I saw that article, however after some testing I found that all my packages were up to date and removing StyleFrame from my code import solved the issue. Add it back in and the issue comes back.

I didn't actually do what the answer suggests:

> I came up with this by inserting a breakpoint() at /ipkernel.py:287 and using w to see what was making the call. If this fix doesn't work for you, worth checking what's making the call in your case.

But I suspect if I did it would be StyleFrame that is making the call.

**Comment by DeepSpace2** [comment]
@helios210 What can I say, I can't reproduce that (installed jupyter just for this).

![image](https://user-images.githubusercontent.com/6841988/91169699-72b8d500-e6e0-11ea-9736-1ba1bb865f1d.png)

![image](https://user-images.githubusercontent.com/6841988/91169979-e35ff180-e6e0-11ea-9ccd-4244ba48bc25.png)

**Comment by helios210** [comment]
Hmm, very odd. Alright I'll go back and insert the break-point as the original poster suggested, see if I can track down what is making the call - perhaps there's something odd about my setup. I'll report back, thanks for investigating.
