### ISSUE TITLE
Option default_grid for Styler.border_style cannot be used

### ISSUE THREAD

**Issue by SampaioTS** [DeepSpace2/StyleFrame#94]
If Styler.border_style is set to 'default_grid', it throws an error if Styler.bg_color is not None (styler.py, line 83). However, before that there seems to be a conversion done to bg_color that turns None values into white (styler.py, line 73), making it such that the option 'default_grid' will always throw an error, which is not consistent with the error message presented ("bg_color and border_type=default_grid can not be used together").

**Comment by DeepSpace2** [comment]
Thanks for reporting. Fixed in version `3.0.6`.
