### ISSUE TITLE
Don't freeze pandas to <x.y.z

### ISSUE THREAD

**Issue by impredicative** [DeepSpace2/StyleFrame#95]
The requirement `pandas<1.2.0` prohibits me from upgrading to pandas 1.2.1. This version requirement (`<1.2.0`) should ideally be unpinned. As a general practice, it's not okay to have a `<` or `<=` pinning in setup.py, but okay to have a `>` or `>=` pinning.

**Comment by impredicative** [comment]
First you ignore the issue. Then you setup this hated and nasty bot to close issues without working on them. It's bad all around.

**Comment by DeepSpace2** [comment]
Hi. 
With all due respect, open-source projects are served "as-is", with no promised SLAs on issues.

Anyway, if you look at the devel branch (where development is being done until a new version is really to be released) you'll see that this is fixed there. In the meanwhile you can get around this by installing pandas before installing styleframe.

**Comment by impredicative** [comment]
There never was a request for an SLA. It is however bad practice to setup a bot effectively to close a legitimate issue without a documented resolution. _Now_ you're saying this issue is resolved in devel, but is it? It is still pinning the max version of Pandas to <1.3, and such pinning is considered poor practice for any Python package. I hope that the `<` pinning can be changed to `>=` instead.

**Comment by DeepSpace2** [comment]
> any such < pinning is considered poor practice for any Python package

Any source that can confirm this? And how exactly does that source handle a breaking change that is going to be introduced in a future major release of the dependency?

**Comment by impredicative** [comment]
The closest I could find is https://packaging.python.org/discussions/install-requires-vs-requirements/ :

> It is not considered best practice to use install_requires to pin dependencies to specific versions, or to specify sub-dependencies (i.e. dependencies of your dependencies). This is overly-restrictive, and prevents the user from gaining the benefit of dependency upgrades.

In the spirit of the above comment, if necessary it should be okay to pin `<` to a major version, e.g. `pandas>=1,<2`.

Also, from http://blog.chrisgorgolewski.org/2017/12/to-pin-or-not-to-pin-dependencies.html (unofficial):

> You want your package to be easy to integrate with other people software stack and thus you should only specify minimally required dependency versions and only if you know that your package will not work with older versions.

My takeaway is that stricter pinning is useful only for end-user applications, not for reusable packages such as StyleFrame.

Lastly, also see https://stackoverflow.com/a/43421973/

**Comment by DeepSpace2** [comment]
> My takeaway is that stricter pinning is useful only for end-user applications, not for reusable packages such as StyleFrame.

I strongly disagree. In the case of styleframe, if either of the "major" dependencies (pandas and openpyxl) are to introduce a breaking change in a future major release ("major release" obviously assume they are using semver) then styleframe *will* break without a prior notice. 

However, I *do* agree that it might be better to only pin major releases, I'll consider that. Thanks for the suggestion.

**Comment by impredicative** [comment]
>  I do agree that it might be better to only pin major releases, I'll consider that

Yes, let's agree to this much. As for packages that run at 0.x.y, e.g. 0.1.2, it could be okay to use say `<0.2` if necessary.

**Comment by impredicative** [comment]
Also, can we agree to a permanent discontinuation of the use of stale bot? It is not fair what it does to any issue. Only if an issue is pending feedback from a reporter should it be marked as stale. If the issue is pending feedback from a maintainer, it should never be marked stale. The objective is to never have stale bot progress to closing any issue as I have sometimes seen it do elsewhere.

**Comment by gansanay** [comment]
Hi,
What is left to be done on this package so that v4.0 is released on pypi?

**Comment by DeepSpace2** [comment]
> Hi,
> What is left to be done on this package so that v4.0 is released on pypi?

Nothing, it has been released :)
