### ISSUE TITLE
New date format for 'MM/DD/YYYY'

### ISSUE THREAD

**Issue by rickmedlin** [DeepSpace2/StyleFrame#97]
Python 3.8
StyleFrame 3.06
OpenPyxl 3.0.5

Hi,

StyleFrame is a great package and I've been able to use the current 'number_format = utils.number_formats.date' when exporting to Excel.  However, that format id DD/MM/YY and my end users would like a four digit year.

Please consider adding a second date format with a four year date:

:cvar str date2: 'DD/MM/YYYY'

**Comment by DeepSpace2** [comment]
Hi.

The values in any of the `utils` classes are just for convivence. You can easily use any custom format directly, for example

    Styler(number_format='DD/MM/YYYY')

**Comment by rickmedlin** [comment]
> Hi.
> 
> The values in any of the `utils` classes are just for convenience. You can easily use any custom format directly, for example
> 
> ```python
> Styler(number_format='DD/MM/YYYY')
> ```

Yes, that format works very well.  Thank you.  However, it renders the two digit date '00' as 1900 instead of 2000.  Is there a workaround for that?

I'm pulling data from an Oracle 18c database.  I tried formatting the data in the query, but doing that caused the query to fail when running from Python.

**Comment by rickmedlin** [comment]
> > Hi.
> > The values in any of the `utils` classes are just for convenience. You can easily use any custom format directly, for example
> > ```python
> > Styler(number_format='DD/MM/YYYY')
> > ```
> 
> Yes, that format works very well. Thank you. However, it renders the two digit date '00' as 1900 instead of 2000. Is there a workaround for that?
> 
> I'm pulling data from an Oracle 18c database. I tried formatting the data in the query, but doing that caused the query to fail when running from Python.

You can disregard my previous comment as I was able to solve the formatting problem in the query.  The custom date format is good to know about, though.  Closing this and thanks again.
